-- SQL for Zynochat Supabase Setup

-- 1. Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    text TEXT NOT NULL,
    uid UUID NOT NULL,
    display_name TEXT,
    photo_url TEXT
);

-- 2. Enable Row Level Security
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies

-- Allow anyone to read messages
CREATE POLICY "Allow public read access" ON public.messages
    FOR SELECT USING (true);

-- Allow authenticated users to insert messages
CREATE POLICY "Allow authenticated insert" ON public.messages
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Allow only the admin user to delete messages
-- Replace 'Kvinit6421@gmail.com' with the actual admin email if needed
CREATE POLICY "Allow admin delete" ON public.messages
    FOR DELETE USING (auth.jwt() ->> 'email' = 'Kvinit6421@gmail.com');

-- 4. Enable Realtime for messages table
-- Note: This usually needs to be done via the Supabase Dashboard under Database -> Replication -> supabase_realtime
-- Or by running:
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
